project:
  type: website
  output-dir: docs

website:
  title: "Jenna Loesberg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: publications.qmd
        text: Publications


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

