---
title: "Curriculum Vitae"
---

# Education

2019 - Current PhD. in Geography, expected August 2025 University of British Columbia, Vancouver BC Supervisor: Dr. Jennifer Williams Dissertation title: “Incorporating understudied factors in demographic responses to climate: Reproductive trade-offs, intraspecific density, and invasive species”

2018 B.A. in Environmental Analysis: Science Concentration with Honors, Pitzer College, Claremont CA Thesis title: “Preliminary examination of seed predator preference in California sage scrub: implications for ecological resistance” [Publication available here](https://link.springer.com/article/10.1007/s11258-021-01163-z)

# Publications

(In Review) Loesberg, J.A. & J.L. Williams. Seasonal climate drives population growth but not costs of reproduction of a perennial wildflower. Submitted to Ecology

(In Review) Clark, J.; Siren, A.; Loesberg, J.; Morelli, T.L. SiMPL Wildlife Magnet: A camera trap tool for detecting all creatures great and small. Submitted to Ecology and Evolution

Hesketh, A\*.*; Loesberg, J.\**; Bledsoe, E.; Karst, J.; Macdonald, E. 2022. Seasonal and annual dynamics of western Canadian boreal forest plant communities: a legacy dataset spanning four decades. Ecology 103:11.\
\* indicates equal contribution

Loesberg, J.A. & W.M. Meyer. 2021. Granivory in California sage scrub: implications for plant invasions and ecosystem conservation. Plant Ecology 222: 1089-1100.

Caspi, T.; L.A. Hartz; A.E. Soto Villa; J.A. Loesberg, C.R. Robins; Meyer, W.M. 2019. Impacts of invasive annuals on soil carbon and nitrogen storage in southern California depend on the identity of the invader. Ecology and Evolution 9(8): 1-14.

# Presentations

2024 Talk Ecological Society of America, Long Beach, CA

2024 Talk Canadian Society of Ecology and Evolution, Vancouver BC

2023 Poster Garry Oak Ecosystems Recovery Team Meeting, Victoria, BC

2023 Talk Biodiversity Research Centre Ecology and Evolution Retreat, Brakendale, BC

2023 Talk Ecological Society of America, Portland, OR

2018 Poster Keck Science Department Thesis Seminar, Claremont CA

# Awards

2024 Department of Geography Graduate Student Travel Award

2024 Graduate Student Travel Award

2021-2025 Four Year Fellowship, University of British Columbia

2021-2025 Four Year Fellowship Tuition Award

2020-2025 President’s Academic Excellence Initiative PhD Award

2019-2025 International Student Tuition Award

2019-2021 Graduate Student Initiative Award

2015 Americorps National Service Award

2014-2018 Pitzer Scholarship, Pitzer College, Claremont CA

# Certificates

2022 Certificate in Data Management and Reproducible Research, Canadian Institute of Ecology and Evolution

# Research Experience

2020-2021 Living Data Project Intern, Canadian Institute of Ecology and Evolution (CIEE)

2019 - Current Graduate Research Assistant, University of British Columbia, Vancouver BC

2017 Field Technician, with Toni Lyn Morelli & Alexej Siren, University of Massachusetts, Amherst MA

2017-2018 Research Technician, with Wallace Meyer III, Pomona College, Claremont CA

2017 Lab Assistant, with Diane Thomson, Keck Science Center, Claremont CA

2016 Field Technician, Rio Mora National Wildlife Refuge, Mora NM

2016 - 2018 Doris Duke Conservation Scholar, Northern Arizona University, Flagstaff AZ

2015 - 2018 Lab Assistant, with Branwen Williams, Keck Science Center, Claremont CA

2015 ‘Imi i ka Lama Collegiate Intern Endangered Wildlife Management Division, Haleakalā National Park, Maui HI

# Teaching Experience

2019 – Current Teaching Assistant, Department of Geography, UBC, Vancouver BC

-   Our Changing Environment: Climate and Ecosystems (GEOB102)

-   Biogeography and Global Change (GEOS 307)

-   Paleoecology: Lessons for the Anthropocene (GEOS 306)

-   Introduction to Biogeography (GEOS 207)

2016 - 2018 Teaching Assistant, Keck Science Center, Claremont CA

-   Introductory Biology Lab (BIO44L)

-   Science and the Environment Lab (EA30L)

# Mentoring

2023 Erin McHugh – Field Assistant; career and academic mentorship Currently: MSc student at University of Toronto 2023

Bellie Zhu – Lab Assistant; mentorship on summer fellowship project (effect of herbivory on annual forb fitness) Currently: MSc student at Columbia University 2022-2023

Ria Raut - Field and Lab Assistant; mentorship on summer fellowship project (effect of herbivory on annual forb fitness) Currently: PhD student at UC Berkeley 2022

Lindsay Worden – Field Assistant Currently: MSc student at University of Victoria 2021-2023

Piper Battersby – Field Assistant; career and academic mentorship; mentorship on summer internship project (Grass Identification Guide for the field site; estimating effect of phenology on seed production)

# Working Groups

Linking climate & demography – Rice University, December 2023 - Reviewing and synthesizing methods to link climatic and demographic data, with a focus on scaling effects of climate to population dynamics

# Discussion Groups

Regular attendee and presenter at:

\- Florum

\- Biodiversity Discussion Group

\- Stats Chats

Leader and Organizer of Florum – Fall 2024
