---
title: "Current and Past Projects"
bibliography: references.bib
---

# Publications

(In Review) **Loesberg, J.A.** & J.L. Williams. Seasonal climate drives population growth but not costs of reproduction of a perennial wildflower. *Submitted to Ecology*

(In Review) Clark, J.; Siren, A.; **Loesberg, J.**; Morelli, T.L. SiMPL Wildlife Magnet: A camera trap tool for detecting all creatures great and small. *Submitted to Ecology and Evolution*

Hesketh, A.\*; **Loesberg, J.**\*; Bledsoe, E.; Karst, J.; Macdonald, E. 2022. Seasonal and annual dynamics of western Canadian boreal forest plant communities: a legacy dataset spanning four decades. Ecology 103:11.  *\* indicates equal contribution*

**Loesberg, J.A.** & W.M. Meyer III. 2021. Granivory in California sage scrub: implications for plant invasions and ecosystem conservation. Plant Ecology 222: 1089-1100.

Caspi, T.; L.A. Hartz; A.E. Soto Villa; **J.A. Loesberg**, C.R. Robins; Meyer, W.M. 2019. Impacts of invasive annuals on soil carbon and nitrogen storage in southern California depend on the identity of the invader. Ecology and Evolution 9(8): 1-14.

# Manuscripts in progress

(In prep) Jennifer L. Williams, Amy L. Angert, Aldo Compagnoni, Ali Campbell, Megan L. DeMarche, Margaret E. K. Evans, Joshua C. Fowler, Edgar J. González, Amy M. Iler, **Jenna A. Loesberg**, Allison M. Louthan, Alexandra Jimenez Martin, Jacob K. Moutouama, Scott W. Nordstrom, William K. Petry, Bilgecan Şen, Seema N. Sheth, Tom E. X. Miller. Linking climate to demography to predict future climate change impacts on population dynamics and persistence. *In preparation to send to Ecology Letters*

(In prep) Scott W. Nordstrom, **Jenna A. Loesberg**, Jennifer L. Williams. Bud emergence phenology advances with simulated drought but only weakly affects population growth of an herbaceous perennial *In preparation to send to PNAS*

(In prep) **Jenna A. Loesberg** & Jennifer L. Williams. Conspecific density and reproductive trade-offs govern population response to climate in a clonal wildflower. *In preparation to send to Journal of Ecology*

(In prep) **Jenna A. Loesberg** & Jennifer L. Williams. Influence of invasive grass neighbors on population growth of a native annual forb under climate change

(In prep) Jeannette Whitton, Evan Hersch, **Jenna A. Loesberg**, Jennifer L. Williams. Life history differences between sexual and asexual populations of a perennial plant, Townsendia hookeri (Asteraceae)
